AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  AssetInsightId:
    Type: String
  RegionShortName:
    Type: String
  Region:
    Type: String
  EnvironmentType:
    Type: String
  ResourceOwner:
    Type: String
  FinancialIdentifier:
    Type: String
  MasterProductAssetInsightId:
    Type: String
  ServiceName:
    Type: String
  ProjectName:
    Type: String
  CodeObjectKey:
    Type: String
  S3BucketTemp:
    Type: String
  S3BucketCicdName:
    Type: String
  S3BucketFinal:
    Type: String
  ProjectNameWithDashes:
    Type: String
  ProjectNameCamel:
    Type: String
  ActivityResultMessageSender:
    Type: String
  BuildVersion:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  GoldenAmi:
    Type: String
  Product:
    Type: String
  StackId:
    Type: String

Resources:
  ResolvedKeyciteStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${Environment}-${ProjectName}-workflow-${RegionShortName}"
      DefinitionString: |
        {
          "Comment": "Resolved Keycite Workflow",
          "StartAt": "ProcessKeycite",
          "States": {
            "ProcessKeycite": {
              "Type": "Pass",
              "End": true
            }
          }
        }
      RoleArn: !GetAtt StateMachineRole.Arn

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSStepFunctionsFullAccess
